CREATE TABLE PRODUCTS(
PRODUCT_ID NUMBER,
PRODUCT_NAME NVARCHAR2(50),
SUPPLIER_ID NUMBER,
CATEGORY_ID NUMBER,
QUANTITY_PER_UNIT NUMBER,
UNIT_PRICE DECIMAL(7,2),
UNITS_IN_STOCK NUMBER,
UNITS_ON_ORDER NUMBER,
REORDER_LEVEL NUMBER,
DISCONTINUED NUMBER,
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY(PRODUCT_ID),
CONSTRAINT SUPPLIER_ID_FK FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
CONSTRAINT CATEGORY_ID_FK FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID));