CREATE TABLE CUSTOMERS(
CUSTOMER_ID NUMBER,
COMPANY_NAME NVARCHAR2(50),
CONTACT_NAME NVARCHAR2(50),
CONTACT_TITLE NVARCHAR2(50),
ADDRESS NVARCHAR2(50),
CITY NVARCHAR2(50),
REGION NVARCHAR2(50),
POSTAL_CODE NVARCHAR2(50),
COUNTRY NVARCHAR2(50),
PHONE NVARCHAR2(50),
FAX NVARCHAR2(50),
CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY(CUSTOMER_ID));