CREATE TABLE TORUM_POLLS_OPTIONS_VOTES(
ID NUMBER,
POLL_OPTION_ID NUMBER,
USER_ID NUMBER,
POLL_OPTION_VOTE_DATE TIMESTAMP,
IP NVARCHAR2(20),
CONSTRAINT POLL_OPTION_VOTE_ID_PK PRIMARY KEY(ID),
CONSTRAINT POLL_OPTION_VOTE_ID_FK FOREIGN KEY(POLL_OPTION_ID) REFERENCES TORUM_POLLS_OPTIONS(ID),
CONSTRAINT USER_POLL_OPTION_VOTE_ID_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID));