CREATE TABLE TORUM_POLLS_OPTIONS(
ID NUMBER,
POST_ID NUMBER,
TITLE NVARCHAR2(64),
POLL_DATE TIMESTAMP,
CONSTRAINT POOL_OPTION_ID_PK PRIMARY KEY(ID),
CONSTRAINT POST_ID_FK FOREIGN KEY(POST_ID) REFERENCES TORUM_POSTS(ID));