CREATE TABLE TORUM_SUBCATEGORIES(
ID NUMBER,
CATEGORY_ID NUMBER,
TITLE NVARCHAR2(45),
DESCRIPTION NVARCHAR2(250),
SUBCAT_DATE TIMESTAMP,
IP NVARCHAR2(20),
CONSTRAINT SUBCATEGORY_ID_PK PRIMARY KEY(ID),
CONSTRAINT CATEGORY_ID_FK FOREIGN KEY(CATEGORY_ID) REFERENCES TORUM_CATEGORIES(ID));