CREATE TABLE TORUM_POSTS(
ID NUMBER,
SUBCATEGORY_ID NUMBER,
USER_ID NUMBER,
PARENT_POST NUMBER,
TITLE NVARCHAR2(90),
CONTENT NVARCHAR2(250),
IS_POOL CHAR(1),
POST_DATE TIMESTAMP,
IP NVARCHAR2(20),
CONSTRAINT POST_ID_PK PRIMARY KEY(ID),
CONSTRAINT SUBCATEGORY_ID_FK FOREIGN KEY(SUBCATEGORY_ID) REFERENCES TORUM_SUBCATEGORIES(ID),
CONSTRAINT USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
CONSTRAINT PARENT_POST_ID_FK FOREIGN KEY(PARENT_POST) REFERENCES TORUM_POSTS(ID));