CREATE TABLE ORDER(
ID NUMBER,
CONSTRAINT ORDER_PK PRIMARY KEY(ID),
CONSTRAINT CHECK_VAL CHECK(ID < 10000),
USER_ID NUMBER UNIQUE,
ROOM_ID NUMBER UNIQUE,
DATE_FROM TIMESTAMP,
DATE_TO TIMESTAMP,
MONEY_PAID DECIMAL(7,2)
);