CREATE TABLE TORUM_CATEGORIES(
ID NUMBER,
TITLE NVARCHAR2(64),
DESCRIPTION NVARCHAR2(250),
CAT_DATE TIMESTAMP,
IP NVARCHAR2(20),
CONSTRAINT CATEGORY_ID PRIMARY KEY(ID));

CREATE TABLE TORUM_SUBCATEGORIES(
ID NUMBER,
CATEGORY_ID NUMBER,
TITLE NVARCHAR2(45),
DESCRIPTION NVARCHAR2(250),
SUBCAT_DATE TIMESTAMP,
IP NVARCHAR2(20),
CONSTRAINT SUBCATEGORY_ID_PK PRIMARY KEY(ID),
CONSTRAINT CATEGORY_ID_FK FOREIGN KEY(CATEGORY_ID) REFERENCES TORUM_CATEGORIES(ID));

CREATE TABLE USERS(
ID NUMBER,
NICK NVARCHAR2(16),
PASSWORD NVARCHAR2(128),
EMAIL NVARCHAR2(128),
USER_DATE TIMESTAMP,
KARMA DECIMAL(9,2),
IP NVARCHAR2(20),
CONSTRAINT USER_ID_PK PRIMARY KEY(ID));

CREATE TABLE TORUM_POSTS(
ID NUMBER,
SUBCATEGORY_ID NUMBER,
USER_ID NUMBER,
PARENT_POST NUMBER,
TITLE NVARCHAR2(90),
CONTENT NVARCHAR2(250),
IS_POOL CHAR(1),
POST_DATE TIMESTAMP,
IP NVARCHAR2(20),
CONSTRAINT POST_ID_PK PRIMARY KEY(ID),
CONSTRAINT SUBCATEGORY_ID_FK FOREIGN KEY(SUBCATEGORY_ID) REFERENCES TORUM_SUBCATEGORIES(ID),
CONSTRAINT USER_ID_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID),
CONSTRAINT PARENT_POST_ID_FK FOREIGN KEY(PARENT_POST) REFERENCES TORUM_POSTS(ID));

CREATE TABLE TORUM_POLLS_OPTIONS(
ID NUMBER,
POST_ID NUMBER,
TITLE NVARCHAR2(64),
POLL_DATE TIMESTAMP,
CONSTRAINT POOL_OPTION_ID_PK PRIMARY KEY(ID),
CONSTRAINT POST_ID_FK FOREIGN KEY(POST_ID) REFERENCES TORUM_POSTS(ID));

CREATE TABLE TORUM_POLLS_OPTIONS_VOTES(
ID NUMBER,
POLL_OPTION_ID NUMBER,
USER_ID NUMBER,
POLL_OPTION_VOTE_DATE TIMESTAMP,
IP NVARCHAR2(20),
CONSTRAINT POLL_OPTION_VOTE_ID_PK PRIMARY KEY(ID),
CONSTRAINT POLL_OPTION_VOTE_ID_FK FOREIGN KEY(POLL_OPTION_ID) REFERENCES TORUM_POLLS_OPTIONS(ID),
CONSTRAINT USER_POLL_OPTION_VOTE_ID_FK FOREIGN KEY(USER_ID) REFERENCES USERS(ID));