--1
CREATE TABLE SUPPLIERS(
SUPPLIER_ID NUMBER,
COMPANY_NAME NVARCHAR2(50),
CONTACT_NAME NVARCHAR2(50),
CONTACT_TITLE NVARCHAR2(50),
ADDRESS NVARCHAR2(50),
CITY NVARCHAR2(50),
REGION NVARCHAR2(50),
POSTAL_CODE NVARCHAR2(50),
COUNTRY NVARCHAR2(50),
PHONE NVARCHAR2(50),
FAX NVARCHAR2(50),
HOME_PAGE NVARCHAR2(50),
CONSTRAINT SUPPLIER_ID_PK PRIMARY KEY(SUPPLIER_ID));
--2
CREATE TABLE CATEGORIES(
CATEGORY_ID NUMBER,
CATEGORY_NAME NVARCHAR2(50),
DESCRIPTION NVARCHAR2(250),
PICTURE BLOB,
CONSTRAINT CATEGORY_ID_PK PRIMARY KEY(CATEGORY_ID));
--3
CREATE TABLE EMPLOYEES(
EMPLOYEE_ID NUMBER,
LAST_NAME NVARCHAR2(50),
FIRST_NAME NVARCHAR2(50),
TITLE NVARCHAR2(50),
TITLE_OF_COURTESY NVARCHAR2(50),
BIRTH_DATE TIMESTAMP,
HIRE_DATE TIMESTAMP,
ADDRESS NVARCHAR2(50),
CITY NVARCHAR2(50),
REGION NVARCHAR2(50),
POSTAL_CODE NVARCHAR2(50),
COUNTRY NVARCHAR2(50),
HOME_PHONE NVARCHAR2(50),
EXTENSION NVARCHAR2(50),
PHOTO BLOB,
NOTES NVARCHAR2(250),
REPORTS_TO NVARCHAR2(50),
CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY(EMPLOYEE_ID));
--4
CREATE TABLE CUSTOMERS(
CUSTOMER_ID NUMBER,
COMPANY_NAME NVARCHAR2(50),
CONTACT_NAME NVARCHAR2(50),
CONTACT_TITLE NVARCHAR2(50),
ADDRESS NVARCHAR2(50),
CITY NVARCHAR2(50),
REGION NVARCHAR2(50),
POSTAL_CODE NVARCHAR2(50),
COUNTRY NVARCHAR2(50),
PHONE NVARCHAR2(50),
FAX NVARCHAR2(50),
CONSTRAINT CUSTOMER_ID_PK PRIMARY KEY(CUSTOMER_ID));
--5
CREATE TABLE SHIPPERS(
SHIPPER_ID NUMBER,
COMPANY_NAME NVARCHAR2(50),
PHONE NVARCHAR2(50),
CONSTRAINT SHIPPER_ID_PK PRIMARY KEY(SHIPPER_ID));
--6
CREATE TABLE PRODUCTS(
PRODUCT_ID NUMBER,
PRODUCT_NAME NVARCHAR2(50),
SUPPLIER_ID NUMBER,
CATEGORY_ID NUMBER,
QUANTITY_PER_UNIT NUMBER,
UNIT_PRICE DECIMAL(7,2),
UNITS_IN_STOCK NUMBER,
UNITS_ON_ORDER NUMBER,
REORDER_LEVEL NUMBER,
DISCONTINUED NUMBER,
CONSTRAINT PRODUCT_ID_PK PRIMARY KEY(PRODUCT_ID),
CONSTRAINT SUPPLIER_ID_FK FOREIGN KEY(SUPPLIER_ID) REFERENCES SUPPLIERS(SUPPLIER_ID),
CONSTRAINT CATEGORY_ID_FK FOREIGN KEY(CATEGORY_ID) REFERENCES CATEGORIES(CATEGORY_ID));
--7
CREATE TABLE ORDERS(
ORDER_ID NUMBER,
CUSTOMER_ID NUMBER,
EMPLOYEE_ID NUMBER,
ORDER_DATE TIMESTAMP,
REQUIRED_DATE TIMESTAMP,
SHIPPED_DATE TIMESTAMP,
SHIP_VIA NUMBER,
FREIGHT NVARCHAR2(50),
SHIP_NAME NVARCHAR2(50),
SHIP_ADDRESS NVARCHAR2(50),
SHIP_CITY NVARCHAR2(50),
SHIP_REGION NVARCHAR2(50),
SHIP_POSTAL_CODE NVARCHAR2(50),
SHIP_COUNTRY NVARCHAR2(50),
CONSTRAINT ORDER_ID_PK PRIMARY KEY(ORDER_ID),
CONSTRAINT CUSTOMER_ID_FK FOREIGN KEY(CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
CONSTRAINT EMPLOYEE_ID_FK FOREIGN KEY(EMPLOYEE_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID));
--8
CREATE TABLE ORDER_DETAILS(
ORDER_ID NUMBER,
PRODUCT_ID NUMBER,
UNIT_PRICE DECIMAL(7,2),
QUANTITY NUMBER,
DISCOUNT NUMBER,
CONSTRAINT ORDER_ID_FK FOREIGN KEY(ORDER_ID) REFERENCES ORDERS(ORDER_ID),
CONSTRAINT PRODUCT_ID_FK FOREIGN KEY(PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID));


























