CREATE TABLE SUPPLIERS(
SUPPLIER_ID NUMBER,
COMPANY_NAME NVARCHAR2(50),
CONTACT_NAME NVARCHAR2(50),
CONTACT_TITLE NVARCHAR2(50),
ADDRESS NVARCHAR2(50),
CITY NVARCHAR2(50),
REGION NVARCHAR2(50),
POSTAL_CODE NVARCHAR2(50),
COUNTRY NVARCHAR2(50),
PHONE NVARCHAR2(50),
FAX NVARCHAR2(50),
HOME_PAGE NVARCHAR2(50),
CONSTRAINT SUPPLIER_ID_PK PRIMARY KEY(SUPPLIER_ID));